### ISSUE TITLE
"Binding a command to a joystick button" contains errors

### ISSUE THREAD

**Issue by iboyperson** [Daltz333/frc-docs#27]
The section [Binding a command to a joystick button](https://frc-docs.readthedocs.io/en/latest/docs/software/commandbased/binding-commands-to-triggers.html#binding-a-command-to-a-joystick-button) has a few flaws

* The `Joystick` classes `getButton()` method is deprecated and only return a boolean of the state.
* The `XboxController` classes `getButton()` method does not even exist.
* Both the `Joystick` and `XboxController` classes enum `Button` is private

Taking these into account the code shown for binding appears to be incorrect. If these are features that will be added in the future this should likely be noted in the docs.

**Comment by Daltz333** [comment]
@Oblarg thoughts on this

**Comment by Oblarg** [comment]
This is for the command framework rewrite, not the current command framework.

**Comment by Oblarg** [comment]
You should probably remove the command-based stuff from master; it should live in develop until the new framework is adopted

**Comment by Daltz333** [comment]
Yeah. I'll do that.

**Comment by Daltz333** [comment]
Closed as this issue is invalid. Feel free to re-open issues if you have any problems with any of the other documentation. Latest documentation is always at 
https://frc-docs.readthedocs.org/en/develop

but please note any documentation involving PID or Command-Based is experimental.
