### ISSUE TITLE
Document the Actuator section of screensteps

### ISSUE THREAD

**Issue by mcm001** [Daltz333/frc-docs#5]

**Comment by Oblarg** [comment]
Please add a bit for java users about using `import static` to reduce verbosity when using solenoid actuators (if there's an equivalent feature for C++, add that too).

**Comment by Oblarg** [comment]
Is anyone currently working on this?  If not, I can probably get it done in the next couple days.

**Comment by mcm001** [comment]
I got about half way through and I'll finish it up over the next couple of days. 

To address the comment from a week ago, I think C++ has an equivalent feature but I'm not sure.
